# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM python:3.12-slim-bookworm

# Install uv
RUN pip install uv

WORKDIR /app

# Copy the application
COPY . .

# Create virtual environment and install dependencies including the package itself
RUN uv venv .venv && \
    uv pip install -r requirements.txt && \
    uv pip install -e .

# Set environment variables for the virtual environment
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app:$PYTHONPATH"

# Environment variables for Jenkins server
ENV JENKINS_URL=https://your-jenkins-server/
ENV JENKINS_USERNAME=your-username
ENV JENKINS_PASSWORD=your-password

# When running the container, add --db-path and a bind mount to the host's db file
ENTRYPOINT ["jenkins-mcp"]
